# .github/workflows/cpp-build.yml
name: C++ Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ compiler
        run: sudo apt-get install g++

      - name: Build with Makefile
        run: make

      - name: Run the program
        run: ./bin/tmm
